
data:
  
model:
  num_layers: 4
  hidden_size: 256

train:
  val_size: 100
  batch_size: 16
  learning_rate: 0.00003
  weight_decay: 0.0001
  eval_strategy: "epoch"
  num_train_epochs: 200
  save_step: 1000
  val_steps: 100

path:
  ckpt: "output/model"
  log: "output/log"